services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    command: -p ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -p ${DATABASE_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: .
    env_file:
     - .env
    command: >
      sh -c "
      alembic upgrade heads &&
      python3 main.py"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg_data: